ALTER TABLE frutarias DROP COLUMN nome;
ALTER TABLE frutarias ADD nome TEXT NOT NULL DEFAULT '';

ALTER TABLE frutarias DROP COLUMN endereco;

ALTER TABLE frutarias DROP COLUMN cnpj;
ALTER TABLE frutarias ADD cnpj INTEGER NOT NULL DEFAULT '';

ALTER TABLE frutarias DROP COLUMN numero;

ALTER TABLE frutarias ADD numero INTEGER NOT NULL DEFAULT 0;