-- Active: 1772562431834@@127.0.0.1@3306
SELECT count(*) FROM FRUTARIA;
#USANDO O * E CONTANDO TODAS AS INFORMACOES#

# SELECT count(ID) FROM FRUTARIA #
# COLOCA O NOME DE UMA COLUNA, E CONTADO SOMENTE OS DADOS NÃO NULOS DESSA COLUNA #


#SELECT COUNT(DISTINCT CNPJ) FROM FRUTARIA #